spring:
  application:
    name: Hotel-App



  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis

server:
  port: 8080